- name: Installing stow
  become: true
  apt: name=stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:iamDrakkir/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    accept_hostkey: yes
    version: main

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./stow_install
