- name: Installing stow
  become: true
  block:
    - name: Install stow on Debian/Ubuntu
      apt:
        name: stow
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Install stow on Arch Linux
      pacman:
        name: stow
      when: ansible_distribution == 'ArchLinux'

- name: Cloning .dotfiles
  git:
    repo: 'git@github.com:iamDrakkir/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    accept_hostkey: yes
    version: main

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./stow_install
