- name: Ensure .config/git directory exists
  file:
    dest: ~/.config/git
    mode: 0700
    state: directory
- name: Ensure .config/git/config exists
  file:
    dest: ~/.config/git/config
    mode: u=rw,g=r,o=r
    state: touch
- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "Hagelin.Rickard@gmail.com"
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "iamDrakkir"
- name: Git personal setup name
  git_config:
    name: core.editor
    scope: global
    value: nvim
