
- name: Remove neovim
  file:
    path: ~/neovim
    state: absent

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    version: nightly

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20 CMAKE_BUILD_TYPE=Release"

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"

- name: Install vim Plugins
  shell: nvim --headless +'PlugInstall --sync' +'PlugUpdate' +qall 
