- name: Install ZSH and set it as the default shell
  become: true
  block:
    - name: Install ZSH on Debian/Ubuntu
      apt:
        name: zsh
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Install ZSH on Arch Linux
      pacman:
        name: zsh
      when: ansible_distribution == 'ArchLinux'

- name: Download zsh-zap
  get_url:
    url: https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh
    dest: /tmp/install.sh

- name: Install zsh-zap
  command:
    cmd: 'zsh /tmp/install.sh'

- name: Create history file
  file:
    path: "{{ lookup('env', 'HOME') }}/.zsh_history"
    state: touch
    mode: "u=rw,g=r,o=r"

- name: Change shell to zsh
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: true
