- name: Install ZSH
  become: true
  apt: name=zsh

- name: Download zsh-zap
  get_url:
    url: https://raw.githubusercontent.com/zap-zsh/zap/master/install.sh
    dest: /tmp/install.sh

- name: Install zsh-zap
  command:
    cmd: 'sh /tmp/install.sh'

- name: create history file
  file:
    path: ~/.zsh_history
    state: touch
    mode: u=rw,g=r,o=r

- name: Change shell to zsh
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: true
