- name: Install ZSH
  become: true
  apt: name=zsh

- name: create history file
  file:
    path: ~/.zhistory
    state: touch
    mode: u=rw,g=r,o=r

- name: Change shell to zsh
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: true
