- name: Install ZSH
  become: true
  apt: name=zsh

- name: create folders for history
  file:
    path: ~/.local/share/zsh/
    state: directory
    mode: '0755'

- name: create history file
  file:
    path: ~/.local/share/zsh/.zhistory
    state: touch
    mode: u=rw,g=r,o=r

- name: Change shell to zsh
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: true
